- name: set up  server
  gather_facts: No
  hosts: elasticsearch_all
  become: yes
  become_method: sudo

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
    - name: Add Elasticsearch apt key.
      apt_key:
        url: https://packages.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository.
      apt_repository:
        repo: "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main"
        state: present
        update_cache: yes

    - name: Install Elasticsearch.
      apt: pkg=elasticsearch state=present
